default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: mysql
  host: db

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
